[package]
name = "FileEncryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = "0.13.1"
rfd = "0.15.0"
aes-gcm = "0.10.3" 
aes-gcm-siv = "0.11.1" 
pbkdf2 = "0.10" 
hmac = "0.12"  
sha2 = "0.10" 
rand = "0.8.5"
chacha20poly1305 = "0.10.1"